---
- name: Make sure the Java certificates are present
  apt:
    name: ca-certificates-java
    default_release: jessie-backports
    state: present
  when: neo4j_manage_java_certificates

- name: Make sure Java version 8 is present
  apt:
    name: openjdk-8-jre-headless
    state: present
  when: neo4j_manage_java

- name: Check the current Java version
  shell: 'java -version'
  changed_when: false
  register: java_version

- name: Set Java 8 as default instead of Java 7
  shell: 'update-java-alternatives -s java-1.8.0-openjdk-amd64'
  when: "'1.8.0' not in java_version.stderr"

- name: Install latest version of Neo4j
  apt:
    name: neo4j
    state: "{{ neo4j_state }}"
    purge: "{{ neo4j_purge }}"
  when:
    - neo4j_version == "latest"

- name: Install specific version of Neo4j
  apt:
    name: "neo4j={{ neo4j_version }}"
    state: "{{ neo4j_state }}"
    purge: "{{ neo4j_purge }}"
  when:
    - neo4j_version != "latest"
